### ISSUE TITLE
wxWidgets error

### ISSUE THREAD

**Issue by peternerlich** [oskusalerma/trelby#382]
I installed the `.deb` package on Ubuntu 15.10, but when I try to start Trelby I get the following Message:

    You seem to have an invalid version
    (3.0.2.0) of wxWidgets installed. This
    program needs version 2.8.

I think this is a bug, because `3.0.2.0` as a higher version as `2.8` surely should work, too.

`uname -a` returns:

    Linux <HOSTNAME> 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oskusalerma** [comment]
wxWidgets is not backwards compatible in all cases, so no, it's not a bug. We can't allow running against untested versions of wxWidgets.

**Comment by oskusalerma** [comment]
This sounded familiar, so I went looking, and yeah, turns out the code did indeed need changes to work with wxPython 3.0, and that I did those changes last summer: https://github.com/oskusalerma/trelby/commit/50c46f2249ca5b094c5e712a872e1dadbd8dfdfa

This is reason number 3924982934892384 we need to do a new release...

**Comment by peternerlich** [comment]
Ok, good to know. `git clone`d it and ran it from `./bin/trelby` without any isues.
